config/routes.rb
Rails.application.routes.draw do  
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users do
    resources :diary_entries # ユーザーに紐づく日記エントリ
    resources :answers # ユーザーに紐づく回答
    resource :profile, only: [:show, :edit, :update]
    resources :chat_messages, only: [:index, :create]
    resources :hobbies, only: [:index, :new, :edit, :create, :destroy]
  end

  resources :emotions do
    resources :emotion_questions # 感情に紐づく質問
  end
  root 'static_pages#top'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  resources :tasks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  #root "tasks#index"
end

app/models/hobby.rb
class Hobby < ApplicationRecord
    belongs_to :user
    mount_uploader :image, HobbyImageUploader
    validate :name_or_image_present

    private

    def name_or_image_present
        if name.blank? && image.blank?
          errors.add(:base, "趣味の名前または画像のいずれかを入力してください")
        end
    end    
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_user
  before_action :set_hobby, only: [:edit, :update, :destroy]

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = current_user.hobbies.build(hobby_params)
    if @hobby.save
      redirect_to user_hobbies_path(@user), notice: "趣味が追加されました"
    else
      render :new, alert: "趣味の追加に失敗しました"
    end
  end

  def index
    @hobbies = @user.hobbies
  end

  def edit
  end

  def update
    if @hobby.update(hobby_params)
      redirect_to user_hobbies_path(@user), notice: "趣味が更新されました"
    else
      render :edit, alert: "趣味の更新に失敗しました"
    end
  end

  def destroy
    @hobby.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("hobby_#{@hobby.id}") }
      format.html { redirect_to user_hobbies_path(@user), notice: "趣味が削除されました" }
    end
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name, :image)
  end

  def set_user
    @user = current_user
  end

  def set_hobby
    @hobby = @user.hobbies.find(params[:id])
  end
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
    def hobby_display_content(hobby)
        if hobby.image.present?
          image_tag(hobby.image.url, class: "mask mask-heart h-32 w-32")
        elsif hobby.name.present?
          content_tag(:div, hobby.name, class: "mask mask-heart bg-primary flex items-center justify-center text-white font-bold h-32 w-32")
        else
          nil
        end
    end
end

app/views/hobbies/create.html.erb
<h1>Hobbies#create</h1>
<p>Find me in app/views/hobbies/create.html.erb</p>

app/views/hobbies/edit.html.erb
<div class="custom-container">
    <!-- 一番上に表示 -->

    <!-- タイトル -->
    <h1 class="text-2xl font-bold mb-4">You're Favorite</h1>
    <div class="flex justify-center items-center mb-4">
        <%= hobby_display_content(@hobby) %>
    </div>

    <!-- エラーメッセージ -->
    <% if @hobby.errors.any? %>
        <div class="alert alert-error w-full max-w-xs">
            <% @hobby.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end %>

    <!-- フォーム -->
    <%= form_with model: @hobby, url: user_hobby_path(@user, @hobby), method: :patch, class: "flex flex-col gap-4 items-center" do |form| %>
        <!-- イメージ -->
        <%= form.file_field :image, class: "file-input file-input-bordered file-input-accent w-full max-w-xs" %>

        <!-- 名前 -->
        <%= form.text_field :name, 
            placeholder: @hobby.name || "あなたの好きなこと", 
            class: "input input-bordered input-primary w-full max-w-xs" %>

        <!-- 送信ボタン -->
        <%= form.submit "更新", class: "btn btn-primary w-full max-w-xs" %>
    <% end %>
</div>

app/views/hobbies/index.html.erb
<div class="custom-container">
  <h1 class="text-2xl font-bold mb-4">What You're Favorites</h1>
    <div class="flex flex-wrap gap-4 justify-center">
      <% @hobbies.each do |hobby| %>
        <%= render partial: 'shared/hobby', locals: { hobby: hobby, user: @user } %>
      <% end %>
    </div>
  <%= link_to '♡追加', new_user_hobby_path(current_user), class: 'btn btn-primary' %>
</div>

app/views/hobbies/new.html.erb
<div class="custom-container">
    <a class="text-lg font-bold">あなたの好きなこと</a>
    <p>Find me in app/views/hobbies/new.html.erb</p>
    <% if @hobby.errors.any? %>
        <div class="alert alert-error w-full max-w-xs">
            <% @hobby.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end %>

  <%= form_with model: @hobby, url: user_hobbies_path(@user), class: "flex flex-col gap-4 items-center" do |form| %>
    <%= form.file_field :image, class: "file-input file-input-bordered file-input-accent w-full max-w-xs" %>
    <%= form.text_field :name, placeholder: "あなたの好きなこと", class: "input input-bordered input-primary w-full max-w-xs" %>
    <%= form.submit "送信", class: "btn btn-primary w-full max-w-xs" %>
  <% end %>
</div>